const settingsConfig = {
  BASE_API_URL: process.env.REACT_APP_BASE_API_URL,
  BACKEND_API_KEY: process.env.REACT_APP_BACKEND_API_KEY,
  BASE_URL: process.env.REACT_APP_BASE_URL,
  ORGANIZATION_ID: process.env.REACT_APP_ORGANIZATION_ID,
  TWITTER_API_URL: process.env.REACT_APP_TWITTER_API_URL,
  ADMIN_API_URL: process.env.REACT_APP_ADMIN_URL,
  TITILE: process.env.REACT_HALMENT_TITLE,
  DESCRIPTION: process.env.REACT_HALMENT_DESCRIPTION,
  EXTENSION_ID: process.env.REACT_APP_FUNKY_EXTENSION_ID,
  ENVIRONMENT: process.env.REACT_APP_ENVIRONMENT,
};

export default settingsConfig;
